import tkinter as tk

def display_details():
    name = name_entry.get()
    age = age_entry.get()
    city = city_entry.get()
    gender = gender_var.get()
    favorite_game = ", ".join(game_var.get())
    result_text.set(f"Name: {name}\nAge: {age}\nCity: {city}\nGender: {gender}\nFavorite Game: {favorite_game}")
    
root = tk.Tk()
root.title("User Details Form")
tk.Label(root, text="Name:").grid(row=0, column=0, sticky=tk.E)
name_entry = tk.Entry(root)
name_entry.grid(row=0, column=1)
tk.Label(root, text="Age:").grid(row=1, column=0, sticky=tk.E)
age_entry = tk.Entry(root, show="*")  # Used a password field to hide age
age_entry.grid(row=1, column=1)
tk.Label(root, text="City:").grid(row=2, column=0, sticky=tk.E)
city_entry = tk.Entry(root)
city_entry.grid(row=2, column=1)
tk.Label(root, text="Gender:").grid(row=3, column=0, sticky=tk.E)
gender_var = tk.StringVar()
tk.Radiobutton(root, text="Male", variable=gender_var, value="Male").grid(row=3, column=1, sticky=tk.W)
tk.Radiobutton(root, text="Female", variable=gender_var, value="Female").grid(row=3, column=1, sticky=tk.E)
tk.Label(root, text="Favorite Game:").grid(row=4, column=0, sticky=tk.E)
game_var = tk.StringVar()
tk.Checkbutton(root, text="Chess", variable=game_var, onvalue="Chess").grid(row=4, column=1, sticky=tk.W)
tk.Checkbutton(root, text="Football", variable=game_var, onvalue="Football").grid(row=4, column=1, sticky=tk.E)
tk.Button(root, text="Submit", command=display_details).grid(row=5, column=1, pady=10)

result_text = tk.StringVar()
result_label = tk.Label(root, textvariable=result_text)
result_label.grid(row=6, column=0, columnspan=2)
root.mainloop()